-- Seed the default report disclaimer so existing installations retain the text
-- that was previously hardcoded in ReportPDFService.
INSERT IGNORE INTO settings (`key`, `value`) VALUES (
    'sds.report_disclaimer',
    'This report was generated by the SDS System. HAP and SARA 313 data is derived from current product formulations on file. Actual emissions may vary based on application conditions. This report is intended for internal environmental compliance use only.'
);

INSERT INTO `schema_migrations` (`version`) VALUES ('009_add_report_disclaimer_setting');
