<?php include dirname(__DIR__) . '/layouts/main.php'; ?>

<?php
$mid     = (int) $manufacturer['id'];
$canEdit = can_edit('private_label');

$addrParts = array_filter([
    (string) ($manufacturer['address'] ?? ''),
    (string) ($manufacturer['city'] ?? ''),
    trim((string) ($manufacturer['state'] ?? '') . ' ' . (string) ($manufacturer['zip'] ?? '')),
    (string) ($manufacturer['country'] ?? ''),
], fn($s) => trim($s) !== '');

$statusBadge = [
    'current' => 'badge-success',
    'stale'   => 'badge-draft',
    'never'   => 'badge-muted',
    'unknown' => 'badge-muted',
    'retired' => 'badge-muted',
];
$sourceBadge = [
    'custom'       => ['Custom', 'badge-editor'],
    'shared_alias' => ['Alias',  'badge-readonly'],
    'base'         => ['Base',   'badge-muted'],
];
$previewLang = $languages[0] ?? 'en';
$langList    = implode(', ', array_map('strtoupper', $languages));
$neverTitle  = 'Not generated by bulk publish until the base SDS is republished — use Publish';
?>

<p><a href="/private-label">&larr; Back to manufacturers</a></p>

<div class="card">
    <div style="display: flex; gap: 1.25rem; align-items: center; flex-wrap: wrap;">
        <?php if (!empty($manufacturer['logo_path'])): ?>
            <img src="<?= e($manufacturer['logo_path']) ?>" alt="Logo" style="max-height: 60px; max-width: 200px;">
        <?php endif; ?>
        <div style="flex: 1; min-width: 200px;">
            <h2 style="margin: 0 0 0.25rem 0;"><?= e($manufacturer['name']) ?></h2>
            <?php if ($addrParts !== []): ?>
                <div class="text-muted"><?= e(implode(', ', $addrParts)) ?></div>
            <?php endif; ?>
            <?php if (!empty($manufacturer['phone']) || !empty($manufacturer['emergency_phone'])): ?>
                <div class="text-muted">
                    <?php if (!empty($manufacturer['phone'])): ?>Phone: <?= e($manufacturer['phone']) ?><?php endif; ?>
                    <?php if (!empty($manufacturer['emergency_phone'])): ?>
                        <?= !empty($manufacturer['phone']) ? '&nbsp;|&nbsp;' : '' ?>Emergency: <?= e($manufacturer['emergency_phone']) ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php if (can_edit('manufacturers')): ?>
            <a href="/manufacturers/<?= $mid ?>/edit" class="btn btn-outline">Edit manufacturer</a>
        <?php endif; ?>
    </div>
</div>

<?php if (trim((string) ($manufacturer['emergency_phone'] ?? '')) === ''): ?>
<div class="alert alert-warning">
    <strong>No emergency phone number.</strong>
    <?= e(\SDS\Services\SDSReadinessService::manufacturerEmergencyPhoneError($manufacturer)) ?>
    <?php if (can_edit('manufacturers')): ?><a href="/manufacturers/<?= $mid ?>/edit">Edit manufacturer &rarr;</a><?php endif; ?>
</div>
<?php endif; ?>

<div class="toolbar">
    <form method="GET" action="/private-label/manufacturer/<?= $mid ?>" class="search-form">
        <input type="text" name="search" value="<?= e($search) ?>" placeholder="Search code, description, or base product...">
        <label style="display: inline-flex; align-items: center; gap: 0.3rem; cursor: pointer; margin: 0;">
            <input type="checkbox" name="show_retired" value="1" <?= $showRetired ? 'checked' : '' ?> onchange="this.form.submit()">
            <span class="text-muted">Show retired</span>
        </label>
        <button type="submit" class="btn btn-sm">Search</button>
        <?php if ($search !== ''): ?>
            <a href="/private-label/manufacturer/<?= $mid ?><?= $showRetired ? '?show_retired=1' : '' ?>" class="btn btn-sm btn-outline">Clear</a>
        <?php endif; ?>
    </form>
    <div style="display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap;">
        <a href="/private-label/documents?manufacturer_id=<?= $mid ?>" class="btn btn-outline">History for all items</a>
        <?php if ($canEdit): ?>
            <form method="POST" action="/private-label/manufacturer/<?= $mid ?>/republish-stale" style="display: inline;">
                <?= csrf_field() ?>
                <button type="submit" class="btn btn-outline" <?= $staleCount === 0 ? 'disabled' : '' ?>
                        title="Republish every active item that is stale or has never been published (frozen items included)"
                        onclick="return confirm(<?= e(json_encode('Republish ' . $staleCount . ' stale / unpublished item(s) for ' . $manufacturer['name'] . '? A new private label SDS version (' . $langList . ') is generated for each.')) ?>)">Republish stale (<?= (int) $staleCount ?>)</button>
            </form>
            <a href="/private-label/manufacturer/<?= $mid ?>/items/create" class="btn btn-primary">+ Add item</a>
        <?php endif; ?>
    </div>
</div>

<?php if (empty($rows)): ?>
    <div class="card" style="text-align: center; padding: 2rem;">
        <p class="text-muted">
            <?php if ($search !== ''): ?>
                No items match "<?= e($search) ?>".
            <?php elseif ($showRetired): ?>
                No private label items for this manufacturer.
            <?php else: ?>
                No active private label items for this manufacturer yet.
            <?php endif; ?>
        </p>
        <?php if ($canEdit && $search === ''): ?>
            <a href="/private-label/manufacturer/<?= $mid ?>/items/create" class="btn btn-primary">Add the first item</a>
        <?php endif; ?>
    </div>
<?php else: ?>
    <p class="text-muted"><?= count($rows) ?> item(s). Each language column links to the latest published PDF for that item.</p>

    <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Description</th>
                <th>Base product</th>
                <th>Latest</th>
                <th>Status</th>
                <?php foreach ($languages as $lang): ?>
                    <th title="<?= e($langNames[$lang] ?? strtoupper($lang)) ?>"><?= e(strtoupper($lang)) ?></th>
                <?php endforeach; ?>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($rows as $row): ?>
            <?php
                $item       = $row['item'];
                $itemId     = (int) $item['id'];
                $isActive   = (int) $item['is_active'] === 1;
                $identity   = $row['identity'];
                $status     = $row['status'];
                $statusCode = (string) ($status['code'] ?? 'unknown');
                $badgeClass = $statusBadge[$statusCode] ?? 'badge-muted';
                [$srcLabel, $srcClass] = $sourceBadge[$identity['source'] ?? 'base'] ?? ['Base', 'badge-muted'];
                $v          = $row['latest_version'];
                $reason     = (string) ($status['reason'] ?? '');
                $title      = $statusCode === 'never' ? $neverTitle : $reason;
                $confirmName = $identity['code'] . ' / ' . $manufacturer['name'];
            ?>
            <tr class="<?= $isActive ? '' : 'text-muted' ?>">
                <td>
                    <strong><?= e($identity['code']) ?></strong>
                    <span class="badge <?= $srcClass ?>" title="Identity source: <?= e($srcLabel) ?>"><?= e($srcLabel) ?></span>
                    <?php if ((int) $item['auto_republish'] !== 1): ?>
                        <br><small class="text-muted" title="Skipped by the base-SDS cascade and bulk publish; only Republish regenerates it">Frozen (manual republish only)</small>
                    <?php endif; ?>
                </td>
                <td><?= e($identity['description']) ?></td>
                <td>
                    <a href="/sds/<?= (int) $item['finished_good_id'] ?>"><?= e($item['fg_product_code'] ?? '') ?></a>
                    <?php if (!empty($item['fg_description'])): ?>
                        <br><small class="text-muted"><?= e($item['fg_description']) ?></small>
                    <?php endif; ?>
                    <?php if (isset($item['fg_is_active']) && (int) $item['fg_is_active'] !== 1): ?>
                        <br><span class="badge badge-muted" title="Inactive finished goods are not republished">FG inactive</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($v === null): ?>
                        <span class="text-muted">&mdash;</span>
                    <?php else: ?>
                        v<?= (int) $v ?><?= !empty($row['latest_date']) ? ' (' . format_date((string) $row['latest_date'], 'm/d/Y') . ')' : '' ?>
                        <br><small class="text-muted"><?= $row['latest_source_fg_version'] !== null ? 'from base v' . (int) $row['latest_source_fg_version'] : 'base version unknown' ?></small>
                        <?php if ($row['latest_code'] !== null && $row['latest_code'] !== $identity['code']): ?>
                            <br><small class="text-muted">printed as <?= e($row['latest_code']) ?></small>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td>
                    <span class="badge <?= $badgeClass ?>" title="<?= e($title) ?>"><?= e($status['label'] ?? ucfirst($statusCode)) ?></span>
                    <?php // PrivateLabelItem::status() supplies the R16 sentence as the reason for
                          // 'never', so this single block covers the never-published hint too. ?>
                    <?php if ($reason !== ''): ?>
                        <br><small class="text-muted"><?= e($reason) ?></small>
                    <?php endif; ?>
                </td>
                <?php foreach ($languages as $lang): ?>
                    <?php $pl = $row['langs'][$lang] ?? null; ?>
                    <td>
                        <?php if ($pl !== null && !empty($pl['id'])): ?>
                            <a href="/private-label/<?= (int) $pl['id'] ?>/download" class="badge badge-success pdf-link" title="<?= e($langNames[$lang] ?? strtoupper($lang)) ?> SDS v<?= (int) $pl['version'] ?>">PDF</a>
                        <?php else: ?>&mdash;<?php endif; ?>
                    </td>
                <?php endforeach; ?>
                <td style="white-space: nowrap;">
                    <?php if ($row['preview_id'] !== null): ?>
                        <a href="/private-label/<?= (int) $row['preview_id'] ?>/preview" class="btn btn-sm btn-outline" target="_blank" title="Latest published snapshot">Preview</a>
                    <?php else: ?>
                        <a href="/private-label/live-preview?item_id=<?= $itemId ?>&amp;lang=<?= e($previewLang) ?>" class="btn btn-sm btn-outline" target="_blank" title="Live preview with current data (nothing published yet)">Preview</a>
                    <?php endif; ?>
                    <a href="/private-label/items/<?= $itemId ?>/history" class="btn btn-sm btn-outline">History</a>
                    <?php if ($canEdit): ?>
                        <?php if ($isActive): ?>
                            <form method="POST" action="/private-label/items/<?= $itemId ?>/publish" style="display: inline;">
                                <?= csrf_field() ?>
                                <button type="submit" class="btn btn-sm btn-primary"
                                        onclick="return confirm(<?= e(json_encode(($v === null ? 'Publish' : 'Republish') . ' private label SDS for ' . $confirmName . '? A PDF is generated for each language (' . $langList . ') from the latest published base SDS.')) ?>)"><?= $v === null ? 'Publish' : 'Republish' ?></button>
                            </form>
                        <?php endif; ?>
                        <a href="/private-label/items/<?= $itemId ?>/edit" class="btn btn-sm">Edit</a>
                        <form method="POST" action="/private-label/items/<?= $itemId ?>/retire" style="display: inline;">
                            <?= csrf_field() ?>
                            <button type="submit" class="btn btn-sm btn-outline"
                                    onclick="return confirm(<?= e(json_encode(($isActive ? 'Retire ' : 'Restore ') . $confirmName . '?' . ($isActive ? ' Retired items are excluded from every republish; their history stays downloadable.' : ''))) ?>)"><?= $isActive ? 'Retire' : 'Restore' ?></button>
                        </form>
                        <?php if (!$row['has_history']): ?>
                            <form method="POST" action="/private-label/items/<?= $itemId ?>/delete" style="display: inline;">
                                <?= csrf_field() ?>
                                <button type="submit" class="btn btn-sm btn-danger"
                                        onclick="return confirm(<?= e(json_encode('Delete ' . $confirmName . '? This item has never been published, so no documents are affected.')) ?>)">Delete</button>
                            </form>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </div>
<?php endif; ?>

<?php include dirname(__DIR__) . '/layouts/footer.php'; ?>
