#!/usr/bin/env php
<?php
/**
 * build-legacy-override-texts.php: builds scripts/data/legacy-override-texts.php,
 * the old automatic SDS text LegacyOverrideMatcher recognises (audit #1, Q12).
 *
 * Input: a directory of files exported from git history, only versions up to
 * 7b7ba32^ (the commit before the #36 editor stopped saving pre-filled text):
 *   translations_<lang>_<sha>.php  = templates/translations/<lang>.php at <sha>
 *   code_<name>_<sha>.php          = src/Services/<name>.php at <sha> (SDSGenerator, HazardEngine)
 * Export recipe (Git Bash, repo root):
 *   OUT=scratch_tmp/legacy-override-src; rm -rf "$OUT"; mkdir -p "$OUT" scripts/data
 *   for lang in en es fr de; do
 *     for c in $(git log --format=%h 7b7ba32^ -- templates/translations/$lang.php); do
 *       git show "$c:templates/translations/$lang.php" > "$OUT/translations_${lang}_$c.php"
 *     done
 *   done
 *   for f in SDSGenerator HazardEngine; do
 *     for c in $(git log --format=%h 7b7ba32^ -- src/Services/$f.php); do
 *       git show "$c:src/Services/$f.php" > "$OUT/code_${f}_$c.php"
 *     done
 *   done
 *   php scripts/build-legacy-override-texts.php "$OUT" scripts/data/legacy-override-texts.php
 *
 * Usage: php scripts/build-legacy-override-texts.php <export-dir> <output.php>
 */

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

use SDS\Services\TextOverrideService;

$dir     = $argv[1] ?? null;
$outFile = $argv[2] ?? null;
if (!is_string($dir) || !is_dir($dir) || !is_string($outFile) || $outFile === '') {
    fwrite(STDERR, "Usage: php scripts/build-legacy-override-texts.php <export-dir> <output.php>\n");
    exit(1);
}

$flatten = static function ($v, array &$set) use (&$flatten): void {
    if (is_string($v)) {
        $n = TextOverrideService::normalize($v);
        if ($n !== '') { $set[$n] = true; }
    } elseif (is_array($v)) {
        foreach ($v as $x) { $flatten($x, $set); }
    }
};

$translations = []; $code = []; $nT = 0; $nC = 0;
$files = glob(rtrim($dir, '/\\') . '/*.php') ?: [];
sort($files);
foreach ($files as $file) {
    $base = basename($file, '.php');
    if (preg_match('/^translations_([a-z]{2})_[0-9a-f]+$/', $base, $m)) {
        $arr = (static fn (string $f) => include $f)($file);
        if (!is_array($arr)) { fwrite(STDERR, "skip (not an array): {$base}\n"); continue; }
        $nT++;
        $translations[$m[1]] ??= [];
        foreach ($arr as $group => $values) {
            if (is_string($group) && preg_match('/^section([1-9]|1[0-6])$/', $group)) {
                $flatten($values, $translations[$m[1]]);
            }
        }
        foreach (['not_determined', 'not_regulated', 'not_applicable'] as $k) {
            if (isset($arr['labels'][$k])) { $flatten($arr['labels'][$k], $translations[$m[1]]); }
        }
        continue;
    }
    if (preg_match('/^code_[A-Za-z]+_[0-9a-f]+$/', $base)) {
        $nC++;
        foreach (token_get_all((string) file_get_contents($file)) as $tok) {
            if (!is_array($tok) || $tok[0] !== T_CONSTANT_ENCAPSED_STRING) { continue; }
            $raw = $tok[1];
            $s = $raw[0] === "'"
                ? str_replace(["\\'", '\\\\'], ["'", '\\'], substr($raw, 1, -1))
                : stripcslashes(substr($raw, 1, -1));
            $n = TextOverrideService::normalize($s);
            if (strlen($n) < 12 || !str_contains($n, ' ') || !preg_match('/[A-Za-z]{3,}/', $n)
                || preg_match('/\b(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE|JOIN)\b/', $n)
                || str_contains($n, '$') || preg_match('#^[/~\#].*[/~\#][a-zA-Z]*$#', $n)) {
                continue;
            }
            $code[$n] = true;
        }
    }
}
$data = ['generated_from' => 'git history up to 7b7ba32^ (scripts/build-legacy-override-texts.php)', 'translations' => [], 'code' => []];
ksort($translations);
foreach ($translations as $lang => $set) {
    $list = array_map('strval', array_keys($set));
    sort($list, SORT_STRING);
    $data['translations'][$lang] = $list;
}
$data['code'] = array_map('strval', array_keys($code));
sort($data['code'], SORT_STRING);
file_put_contents($outFile, "<?php\n// Generated by scripts/build-legacy-override-texts.php; do not edit by hand.\n// Old automatic SDS text (audit #1 / Q12) for SDS\\Services\\LegacyOverrideMatcher.\n\nreturn " . var_export($data, true) . ";\n");
echo "Translation files: {$nT}, code files: {$nC}\n";
foreach ($data['translations'] as $lang => $list) { echo "  {$lang}: " . count($list) . " strings\n"; }
echo "  code: " . count($data['code']) . " strings\nWrote {$outFile}\n";
exit(0);
